version: '3'
services:
  mongo:
    container_name: db_app-envio-email
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      # MONGO_INITDB_DATABASE: ${DB_NAME}
